# Generated by Django 5.1.6 on 2025-02-24 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zazdrava', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout',
            old_name='created_at',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='workout',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
